# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Tech Matters
tagline:          "manku-timma's blog"

paginate:         5

# Custom vars
version:          2.0.0
